[project]
name = "kubert"
version = "0.1.0"
description = "Simple tool to allow logging into multiple Kubernetes clusters simultaneously"
readme = "README.md"
authors = [
    { name = "mike", email = "mspiegel@spoton.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pyyaml>=6.0.3",
    "boto3>=1.40.65",
    "iterfzf>=1.8.0.62.0",
    "click>=8.3.0",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
]

[project.scripts]
kubert = "kubert.cli:main"
assume-role = "kubert.assume_role:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"
